(function(){
'use strict';
const URL='https://cdidgehrcnapaqdxmhok.supabase.co';
const KEY='sb_publishable_bj2ER2qqjx6bA7GA57-N3w_SNMPkooE';
const STORE='languagesDepartmentAuth_v2';
const SIGNUP=URL+'/functions/v1/languages-signup';
const PERMS={dashboard:'Dashboard',culture:'Country Culture',nations:'Nation Work',team:'Team & Performance',operations:'Operations',meetings:'Meetings',reports:'Reports',settings:'Administration',workspace_read:'Shared Data — Read',workspace_write:'Shared Data — Write',data_write:'Create / Edit Records',data_delete:'Delete Records'};
let A=null,P=null;
function h(token){const x={'apikey':KEY,'Content-Type':'application/json'};if(token)x.Authorization='Bearer '+token;return x}
function save(a){A=a;localStorage.setItem(STORE,JSON.stringify(a))}
function clear(){A=P=null;localStorage.removeItem(STORE);sessionStorage.removeItem('languagesSession');session=null;settingsUnlocked=false;clearInterval(syncTimer)}
function superAdmin(){return P?.role==='super_admin'}
function perm(k){return k==='culture'?!!P:(superAdmin()||P?.permissions?.[k]===true)}
function writeOK(){return superAdmin()||perm('data_write')}
function deleteOK(){return superAdmin()||perm('data_delete')}
function authMessage(msg,error=false){const e=document.getElementById('ldAuthMessage');if(!e)return;e.className=error?'notice':'info';e.textContent=msg;e.classList.remove('hidden')}
async function refresh(){const a=A||JSON.parse(localStorage.getItem(STORE)||'null');if(!a?.refresh_token)return null;const r=await fetch(URL+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:h(),body:JSON.stringify({refresh_token:a.refresh_token})});if(!r.ok){clear();return null}const d=await r.json();save(d);return d}
async function profile(uid){let a=A||JSON.parse(localStorage.getItem(STORE)||'null');if(!a?.access_token)return null;let r=await fetch(URL+'/rest/v1/language_app_users?user_id=eq.'+encodeURIComponent(uid)+'&select=*',{headers:h(a.access_token)});if(r.status===401){a=await refresh();if(!a)return null;r=await fetch(URL+'/rest/v1/language_app_users?user_id=eq.'+encodeURIComponent(uid)+'&select=*',{headers:h(a.access_token)})}if(!r.ok)return null;return (await r.json())[0]||null}
function apply(p,u){P=p;const elevated=['super_admin','admin','manager'].includes(p.role);session={type:elevated?'admin':'member',name:p.full_name||u.email||'User',memberId:p.member_id||u.id,userId:u.id,email:u.email,role:p.role};settingsUnlocked=perm('settings')}
async function login(email,password){const r=await fetch(URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:h(),body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||d.msg||d.error||'Sign in failed');save(d);const p=await profile(d.user.id);if(!p)throw new Error('This account is not registered for Languages Department.');if(p.status==='suspended')throw new Error('This account is suspended. Contact the Super Admin.');apply(p,d.user);if(perm('workspace_read'))await cloudPull(false);enterApp()}
async function signup(name,email,password){const r=await fetch(SIGNUP,{method:'POST',headers:h(),body:JSON.stringify({full_name:name,email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to create account');authMessage('Account created successfully. You can now sign in as a user.')}
async function logout(){try{if(A?.access_token)await fetch(URL+'/auth/v1/logout',{method:'POST',headers:h(A.access_token)})}catch(e){}clear();showAuth()}
function installAuthUI(){const root=document.getElementById('loginScreen');root.innerHTML=`<div class="login-card"><div class="login-logo">LD</div><h1>Languages Department Team System</h1><p id="ldAuthIntro">Sign in with your approved email account.</p><div class="tabs"><button type="button" class="tab active" id="ldLoginTab">Sign In</button><button type="button" class="tab" id="ldSignupTab">Create Account</button></div><form id="ldLogin" class="form-stack"><div class="field"><label>Email</label><input class="input" name="email" type="email" autocomplete="email" required></div><div class="field"><label>Password</label><input class="input" name="password" type="password" autocomplete="current-password" required></div><button class="btn btn-primary" type="submit">Sign In</button></form><form id="ldSignup" class="form-stack hidden"><div class="field"><label>Full Name</label><input class="input" name="name" autocomplete="name" required></div><div class="field"><label>Email</label><input class="input" name="email" type="email" autocomplete="email" required></div><div class="field"><label>Password</label><input class="input" name="password" type="password" minlength="8" autocomplete="new-password" required></div><button class="btn btn-primary" type="submit">Create Account</button></form><div id="ldAuthMessage" class="info hidden" style="margin-top:14px"></div></div>`;const lt=document.getElementById('ldLoginTab'),st=document.getElementById('ldSignupTab'),lf=document.getElementById('ldLogin'),sf=document.getElementById('ldSignup');lt.onclick=()=>{lf.classList.remove('hidden');sf.classList.add('hidden');lt.classList.add('active');st.classList.remove('active');document.getElementById('ldAuthIntro').textContent='Sign in with your approved email account.'};st.onclick=()=>{sf.classList.remove('hidden');lf.classList.add('hidden');st.classList.add('active');lt.classList.remove('active');document.getElementById('ldAuthIntro').textContent='Create an account. A Super Admin must approve access before you can enter.'};lf.onsubmit=async e=>{e.preventDefault();const f=new FormData(lf);try{authMessage('Signing in…');await login(String(f.get('email')||'').trim(),String(f.get('password')||''))}catch(x){authMessage(x.message,true)}};sf.onsubmit=async e=>{e.preventDefault();const f=new FormData(sf);try{authMessage('Creating account…');await signup(String(f.get('name')||'').trim(),String(f.get('email')||'').trim(),String(f.get('password')||''));sf.reset()}catch(x){authMessage(x.message,true)}}}
function showAuth(msg=''){session=null;document.getElementById('app').classList.add('hidden');document.getElementById('loginScreen').classList.remove('hidden');if(msg)authMessage(msg)}
isAdmin=function(){return ['super_admin','admin','manager'].includes(P?.role)};
currentMember=function(){return state.team.find(x=>x.id===session?.memberId)||{id:session?.memberId||session?.userId||'',name:session?.name||'User',role:P?.role||'User',nationIds:[]}};
openSettingsGate=function(){if(!perm('settings'))return toast('Administration permission required');settingsUnlocked=true;currentPage='settings';renderNav();render()};
const oldEnter=enterApp;enterApp=function(){oldEnter();document.getElementById('sessionRole').textContent=(P?.role||'user').replace('_',' ').replace(/\b\w/g,c=>c.toUpperCase())};
renderNav=function(){let rows=(isAdmin()?NAV_ADMIN:NAV_MEMBER).filter(([v])=>perm(v));if(superAdmin())rows.push(['access','Access Control','◈']);if(!rows.length)rows=[['dashboard','Overview','◉']];if(!rows.some(x=>x[0]===currentPage))currentPage=rows[0][0];document.getElementById('nav').innerHTML=rows.map(([v,l,i])=>`<button data-page="${v}" class="${currentPage===v?'active':''}"><span class="nav-ico">${i}</span>${esc(l)}</button>`).join('');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{currentPage=b.dataset.page;renderNav();render();document.getElementById('sidebar').classList.remove('open')})};
const oldRender=render;render=function(){if(!session)return showAuth();if(currentPage!=='access'&&!perm(currentPage)){const row=(isAdmin()?NAV_ADMIN:NAV_MEMBER).find(([v])=>perm(v));currentPage=row?.[0]||'dashboard'}oldRender()};
const oldOpenForm=openForm;openForm=function(type,id){if(type==='member'&&id===session?.memberId)return oldOpenForm(type,id);if(!writeOK())return toast('Create / edit permission required');return oldOpenForm(type,id)};
const oldRemove=removeRecord;removeRecord=function(key,id){if(!deleteOK())return toast('Delete permission required');return oldRemove(key,id)};
cloudHeaders=function(){return {'apikey':KEY,'Authorization':'Bearer '+(A?.access_token||''),'Content-Type':'application/json'}};
cloudPull=async function(show=false){if(!perm('workspace_read'))return show&&toast('Shared data read permission required');try{const r=await fetch(URL+'/rest/v1/language_workspaces?workspace_id=eq.languages-department&select=payload,revision,updated_at',{headers:cloudHeaders()});if(r.status===401&&await refresh())return cloudPull(show);if(!r.ok)throw new Error(await r.text());const rows=await r.json();if(!rows.length)return;state=mergeStates(state,normalize(rows[0].payload));state.settings.lastCloudRevision=num(rows[0].revision);saveLocal();if(session)render();if(show)toast('Shared workspace loaded')}catch(e){console.error(e);if(show)toast('Cloud pull failed')}};
cloudPush=async function(show=false){if(!perm('workspace_write'))return show&&toast('Shared data write permission required');try{const revision=num(state.settings.lastCloudRevision)+1,payload={workspace_id:'languages-department',payload:state,revision,updated_at:isoNow()};const r=await fetch(URL+'/rest/v1/language_workspaces?on_conflict=workspace_id',{method:'POST',headers:{...cloudHeaders(),'Prefer':'resolution=merge-duplicates,return=representation'},body:JSON.stringify(payload)});if(r.status===401&&await refresh())return cloudPush(show);if(!r.ok)throw new Error(await r.text());state.settings.lastCloudRevision=revision;saveLocal();if(show)toast('Shared workspace synchronized')}catch(e){console.error(e);toast('Cloud push failed')}};
scheduleSync=function(){clearInterval(syncTimer);if(state.settings.cloud.autoSync&&perm('workspace_read'))syncTimer=setInterval(async()=>{await cloudPull(false);if(perm('workspace_write'))await cloudPush(false)},60000)};
accountAction=function(a){document.getElementById('accountMenu').classList.add('hidden');if(a==='backup')exportBackup();else if(a==='restore')document.getElementById('restoreInput').click();else if(a==='profile'){if(session?.memberId&&state.team.some(x=>x.id===session.memberId))oldOpenForm('member',session.memberId);else toast('No team profile linked to this account')}else if(a==='logout')logout()};
actionButtons=function(key,id,edit=true){return `<div class="row-actions">${edit&&writeOK()?`<button class="btn btn-secondary btn-sm" data-edit="${key}" data-id="${id}">Edit</button>`:''}${deleteOK()?`<button class="btn btn-danger btn-sm" data-delete="${key}" data-id="${id}">Delete</button>`:''}</div>`};
function roleOptions(v,self){return ['super_admin','admin','manager','user'].map(x=>`<option value="${x}" ${x===v?'selected':''} ${self&&x!=='super_admin'?'disabled':''}>${x.replace('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}</option>`).join('')}
function statusOptions(v,self){return ['pending','active','suspended'].map(x=>`<option value="${x}" ${x===v?'selected':''} ${self&&x!=='active'?'disabled':''}>${x[0].toUpperCase()+x.slice(1)}</option>`).join('')}
async function users(){const r=await fetch(URL+'/rest/v1/language_app_users?select=*&order=created_at.desc',{headers:h(A.access_token)});if(!r.ok)throw new Error('Unable to load accounts');return r.json()}
pages.access=function(){return superAdmin()?pageHeader('Access Control','Approve new accounts, assign roles and grant exact access.')+'<div class="info" style="margin-bottom:12px">New signups remain pending until you activate them. Module permissions control what appears in the system; Shared Data permissions control database synchronization.</div><div id="ldUsers"><div class="card empty">Loading accounts…</div></div>':'<div class="card empty">Super Admin access required.</div>'};
async function loadUsers(){const host=document.getElementById('ldUsers');if(!host||!superAdmin())return;try{const all=await users();host.innerHTML=all.map(u=>{const self=u.user_id===A.user.id,p=u.permissions||{};return `<div class="card" style="margin-bottom:12px" data-uid="${u.user_id}"><div class="split"><div><h3 style="margin:0 0 4px">${esc(u.full_name||u.email)}</h3><div class="muted">${esc(u.email)}</div></div>${badge(u.status)}</div><div class="form-grid" style="margin-top:12px"><div class="field"><label>Role</label><select data-role ${self?'disabled':''}>${roleOptions(u.role,self)}</select></div><div class="field"><label>Status</label><select data-status ${self?'disabled':''}>${statusOptions(u.status,self)}</select></div><div class="field full"><label>Link to Team Member (optional)</label><select data-member>${options(state.team.map(m=>[m.id,m.name]),u.member_id||'','No linked team member')}</select></div><div class="subhead">Permissions</div><div class="check-grid full">${Object.entries(PERMS).map(([k,l])=>`<label class="check-row"><input type="checkbox" data-p="${k}" ${(u.role==='super_admin'||p[k])?'checked':''} ${u.role==='super_admin'?'disabled':''}><span>${esc(l)}</span><small>${['workspace_write','data_write','data_delete'].includes(k)?'Write':'Access'}</small></label>`).join('')}</div></div><div class="actions" style="margin-top:12px"><button class="btn btn-primary" data-save="${u.user_id}">Save Access</button></div></div>`}).join('');host.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>saveUser(b.dataset.save))}catch(e){host.innerHTML='<div class="notice">'+esc(e.message)+'</div>'}}
async function saveUser(id){const c=document.querySelector(`[data-uid="${id}"]`);if(!c)return;const self=id===A.user.id,role=self?'super_admin':c.querySelector('[data-role]').value,status=self?'active':c.querySelector('[data-status]').value,member_id=c.querySelector('[data-member]').value||null,permissions={};c.querySelectorAll('[data-p]').forEach(x=>permissions[x.dataset.p]=role==='super_admin'||x.checked);const r=await fetch(URL+'/rest/v1/language_app_users?user_id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{...h(A.access_token),'Prefer':'return=minimal'},body:JSON.stringify({role,status,member_id,permissions,approved_by:A.user.id,approved_at:status==='active'?isoNow():null})});if(!r.ok)return toast('Access update failed');toast('User access updated');loadUsers()}
const oldBind=bindPage;bindPage=function(){oldBind();if(currentPage==='access')loadUsers()};
async function boot(){clearInterval(syncTimer);session=null;installAuthUI();showAuth();try{const saved=JSON.parse(localStorage.getItem(STORE)||'null');if(saved?.access_token&&saved?.user?.id){A=saved;const p=await profile(saved.user.id);if(p&&p.status!=='suspended'){apply(p,saved.user);if(perm('workspace_read'))await cloudPull(false);enterApp();return}if(p?.status==='suspended')authMessage('This account is suspended. Contact the Super Admin.')}}catch(e){console.error(e);clear()}showAuth()}
boot();
})();
